[[main]]
none = "none"

[[main]]
name = "Games"
pageRef = "Games"
weight = 1

[[main]]
name = "Socratic Smackdown"
pageRef = "Games/socratic-smackdown"
parent = "Games"
weight = 6

[[main]]
name = "Belgian Feather Bowling : On the Go!"
pageRef = "Games/bfb"
parent = "Games"
weight = 9

[[main]]
name = "Croaky Climber"
pageRef = "Games/croaky-climber"
parent = "Games"
weight = 10

[[main]]
name = "Lost Echoes"
pageRef = "Games/lost-echoes"
parent = "Games"
weight = 11

[[main]]
name = "Bleak Friday"
pageRef = "Games/bleak-friday"
parent = "Games"
weight = 12

[[main]]
name = "Graphics"
pageRef = "Graphics"
weight = 2

[[main]]
name = "Callisto Engine"
pageRef = "Graphics/callisto-engine"
parent = "Graphics"
weight = 13

[[main]]
name = "Gerstner Waves"
pageRef = "Graphics/gerstner-waves"
parent = "Graphics"
weight = 7

[[main]]
name = "Volumetric Clouds"
pageRef = "Graphics/volumetric-clouds"
parent = "Graphics"
weight = 14

[[main]]
name = "Unity Animation System"
pageRef = "Graphics/custom-unity-animation-system"
parent = "Graphics"
weight = 15

[[main]]
name = "Vulkan Renderer"
pageRef = "Graphics/vulkan-renderer"
parent = "Graphics"
weight = 16

[[main]]
name = "Tech Art"
pageRef = "Tech Art"
weight = 3

[[main]]
name = "Procedural Rocks & Columns"
pageRef = "Tech Art/procedural-rocks-&-pillars"
parent = "Tech Art"
weight = 8

[[main]]
name = "Maya Voxelizer"
pageRef = "Tech Art/maya-voxelizer"
parent = "Tech Art"
weight = 17

[[main]]
name = "Rigging & Tools"
pageRef = "Tech Art/rigging-&-tools"
parent = "Tech Art"
weight = 18

[[main]]
name = "All Projects"
pageRef = "All Projects"
weight = 4

[[main]]
name = "About Me"
pageRef = "About Me"
weight = 5

[[footer]]
none = "none"
